version: '3.3'

services:

  trilium:
    image: zadam/trilium
    container_name: trilium   
    restart: unless-stopped
    ports:
      - "8200:8080"
    volumes:
      - ./trilium-data:/home/node/trilium-data
